install ack
install ant
install apple-gcc42
install autoconf
install automake
install cmake
install ctags
install gettext
install git
install glib
install gnupg
install go
install graphicsmagick
install jpeg
install libevent
install libffi
install libgpg-error
install libksba
install libpng
install libtool
install libyaml
install mercurial
install mongodb
install mysql
install openssl
install openssl098
install phantomjs
install pkg-config
install readline
install redis
install sqlite
install sshfs
install vim
install wget
install xz
install zeromq22
