---
last_check:
  etag: W/"21eb84c207320e35b005f44aa64e4ff1"
  version: 1.8.2
  at: 1462619173
checked_completion: true
completion_version: 1.8.2
endpoints:
  https://api.travis-ci.org/:
    access_token: 
repos:
  digitalronin/peepchat:
    endpoint: https://api.travis-ci.org/
  digitalronin/peepchat-api:
    endpoint: https://api.travis-ci.org/
